# Automatically generated by configure
# Configured with: './configure'
CC = /opt/FunKey-sdk-2.0.0/bin/arm-funkey-linux-musleabihf-gcc
CXX = /opt/FunKey-sdk-2.0.0/bin/arm-funkey-linux-musleabihf-g++
AS = /opt/FunKey-sdk-2.0.0/bin/arm-funkey-linux-musleabihf-as
STRIP = /opt/FunKey-sdk-2.0.0/bin/arm-funkey-linux-musleabihf-strip
CFLAGS += -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Ofast   -mfpu=neon -marm -I/opt/FunKey-sdk-2.0.0/arm-funkey-linux-musleabihf/sysroot/usr/bin/../../usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result
ASFLAGS +=  -mfpu=neon
LDFLAGS += 
LDLIBS += -L/opt/FunKey-sdk-2.0.0/arm-funkey-linux-musleabihf/sysroot/usr/bin/../../usr/lib -lSDL -lpthread -lpng  -lm -lz

ARCH = arm
PLATFORM = generic
SOUND_DRIVERS = sdl
